### ISSUE TITLE
Add a schema for raml2obj output

### ISSUE THREAD

**Issue by kevinrenskers** [raml2html/raml2obj#13]
We'd like to get a schema of the output that raml2obj generates.

JSON representation of the world-music-api example RAML file: https://github.com/raml2html/raml2obj/blob/develop/test/worldmusic.json. This can be used as a starting point.

**Comment by kevinrenskers** [comment]
http://jsonschema.net could be useful as well.

**Comment by sichvoge** [comment]
Thanks Kevin. Just to highlight, that schema will help to provide useful feedback to create a better parser output.
