### ISSUE TITLE
TypeError: result.expand is not a function

### ISSUE THREAD

**Issue by marvinhagemeister** [raml2html/raml2obj#17]
I have a raml 1.0 file which I passed through the beta of raml2html. raml2obj throws a `TypeError: result.expand is not function`. This occurs because `result.expand` is `undefined`  https://github.com/raml2html/raml2obj/blob/develop/index.js#L262

**Comment by kevinrenskers** [comment]
All unit tests pass, and I am able to parse my files just fine. I am guessing your RAML file has a problem, or that your `npm install` had some problems maybe?

**Comment by marvinhagemeister** [comment]
I'll see if I can get a reproducible test case next week

**Comment by marvinhagemeister** [comment]
As promised, here is a simple test case, which reproduces the error:

```raml
#%RAML 1.0 Library
types:
  message:
    properties:
      id:
        type: string
        required: true
```

**Comment by kevinrenskers** [comment]
Hm but this is not the type of file you'd use with raml2html or raml2obj, it's not a "root" raml file. Of course it shouldn't throw this error, instead it show throw the original error from the official raml parser, so I'll work on that. Thanks for the example!

**Comment by marvinhagemeister** [comment]
Oh I see, thanks for clearing it up. I have multiple `.raml` files here and indeed there is a root file.

**Comment by kevinrenskers** [comment]
Nonetheless, the next version will have improved error messaging :)
