### ISSUE TITLE
Exception thrown when using libraries

### ISSUE THREAD

**Issue by lijithv** [raml2html/raml2obj#18]
There has been an issue with raml-js-parser-2 where it used to throw an error if libraries are used. Please refer to [#553](https://github.com/raml-org/raml-js-parser-2/issues/553)

This has been fixed in raml-1-parser **1.1.9** and raml2obj has to be updated to use the same.

**Comment by kevinrenskers** [comment]
Done, thanks.

**Comment by lijithv** [comment]
Cool. Thanks @kevinrenskers. I tested raml2html@4.0.0-beta18 with the new release of raml2obj and its not throwing an exception anymore when using libraries.
