### ISSUE TITLE
Is there a way to make it work in a browser?

### ISSUE THREAD

**Issue by jarrodek** [raml2html/raml2obj#19]
I tried to use browserify  but I have a lot of problem when including `datatype-expansion`. It uses Google JS Library (`goog` scripts) that uses some dirty hacks for including some variables into the global namespace. So they have this `nodeGlobalRequire` function which can be processed by `browserify`. It may work in node but definitely will not work in the browser.

I also tried to work with the library to override it to work with native node (so it can be transferred to browser environment) but it would be rewriting whole thing.
Maybe there's a solution that I'm not aware of?

**Comment by kevinrenskers** [comment]
You'd probably have to ask the `datatype-expansion` guys if the problem lies there, but I doubt it would work anyway because raml2obj uses the Node `fs` API.

Not sure why you'd want to use it in the browser anyway? Are you using raml2obj standalone (as in, not with raml2html or raml2obj)?

**Comment by jarrodek** [comment]
Thanks for quick reply.
I'm using the library in web based projects. It's a web app(s) that uses RAML or rather it's parser's JS output. I'll also contact `datatype-expansion` team to ask them about this.

**Comment by kevinrenskers** [comment]
You could just use the official raml-parser instead of raml2obj maybe?

If there are any changes you can contribute to this project so that it becomes usable in a browser, I'd love to see a PR. For now I am closing this ticket though.

**Comment by jarrodek** [comment]
I am using the RAML JS parser. The problem is that the output is not what I call usable output ;) I have 4th approach to write my own normalizer and data type expander when someone suggested me to use this library. So I was trying to use it in my projects. I already have data normalization ready (like your `arrayToObject` and `objecTtoArray` function but I still missing a part where I have data types in canonical form where I can use type definition in resources - for example - without additional computation of properties.
Anyways thanks for the response.

**Comment by kevinrenskers** [comment]
True, their output is kind of horrible to work with :(
