### ISSUE TITLE
Invalid error messages when file does not exist

### ISSUE THREAD

**Issue by blakeembrey** [raml2html/raml2obj#2]
From https://github.com/raml-org/raml-js-parser/issues/153, `raml2obj` is incorrectly assuming that because it can't load the file it's a source string. See https://github.com/kevinrenskers/raml2obj/blob/master/index.js#L85-L91. If it doesn't exist on the filesystem, it passes it into `load`. This results in a poor user experience and confusion.

P.S. Your `if` check is against a string so no need to try converting to `string`.

**Comment by kevinrenskers** [comment]
This is no longer an issue in 4.0.0-beta1 and beyond.
