### ISSUE TITLE
object properties don't inherit correctly

### ISSUE THREAD

**Issue by DataGreed** [raml2html/raml2obj#27]
When using example from docs:

```
#%RAML 1.0
title: Example with responses
mediaType: application/json
types:
  Invoice:
    properties:
      amount:
        type: number
        minimum: 0
      vendorName:
/invoices:
  get:
    responses:
      200:
        body:
          type: Invoice
          properties:
            id: number
```

I get just Invoice fields in output. Id field specified in properties is not rendered. The same problem goes when specifying this properties in one of resourceTypes (though it may be the same problem, dunno).

Same thing goes if you use this example:

```
types:
  Person:
    type: object
    properties:
      name: string
  Employee:
    type: object
    properties:
      employeeNr: integer
  Teacher:
    type: [ Person, Employee ]
```

In this case no properties are rendered at all

**Comment by psychoo118** [comment]
I also experienced this issue and the result of my investigation was that its source is in raml-org/raml-js-parser-2. The output of the parser does not contain the inherited properties so the issue is there.
My workaround was to define Teacher in the following way:

```
Teacher:
  type:
    - Person
    - Employee
```

**Comment by sichvoge** [comment]
@psychoo118 did you raise it on their repo?

**Comment by psychoo118** [comment]
Now I'm not sure of the cause, I will look into it tomorrow

**Comment by kevinrenskers** [comment]
I am going to close old issues, and will ask that new bug reports instead be created as a pull request with a failing unit test. Sorry, but I just don't have the time and energy to do it all alone :/

See also https://github.com/raml2html/raml2obj/blob/develop/CONTRIBUTING.md. Thanks!
