### ISSUE TITLE
Look into upgrading datatype-expansion dependency

### ISSUE THREAD

**Issue by kevinrenskers** [raml2html/raml2obj#28]
Newest version of datatype-expansion is 0.1.1 but it causes one failing test

```
  32 passing (3s)
  1 failing

  1) raml2obj worldmusic.raml should test the /api methods:

      AssertionError: 'union' === 'object'
      + expected - actual

      -union
      +object
      
      at Context.it (test/worldmusic.spec.js:100:14)
```

**Comment by nickwb** [comment]
Behavior of unions changed with datatype-expansion `0.1.0`.

While fixing the unit test is easy, it's likely to regress existing users who have union types in their APIs.

I'm also not sure that it will the desired behavior. It's a bit weird - but union types seem to be getting "pushed up", so you have root types with union sub-properties which end up taking on every permutation of its union child properties. In terms of **raml2html** and *raml2md**, I doubt this will be the desired behavior.

**Comment by kevinrenskers** [comment]
Regressions are fine if we do it with a major update, so 5.0.0 for example. As for this particular instance, yeah I'm not sure either. @sichvoge, do you maybe have any insight here?

**Comment by kevinrenskers** [comment]
(Oh yeah in case you didn't know, Christian aka @sichvoge works with the RAML Workgroup, is involved with raml2html as well, and is the author of datatype-expansion.)

**Comment by sichvoge** [comment]
Wouldn't say I am the author, but I am literally sitting next to him :) I'll speak to him.

**Comment by antoniogarrote** [comment]
Hi, @kevinrenskers I have taken a look at your spec. 
The correct canonical type is the one generated by version 0.1.1.

You are computing the canonical form of `RAMLDataType` that includes one union `CatOrDog` and an object with an optional property `NilValue`. With that input, the expected output of the canonical form is a single union at the top level with types covering all the possible combinations of Dog, Cat, nil property, not nil property.

The output with the old version of the library is incorrect.

If you just want a regular and predictable output for the type, you can just compute the expanded form without getting to the canonical.

Cheers.

**Comment by kevinrenskers** [comment]
Hey guys, what's the status of this? Can we update to datatype-expansion 0.1.1 and solve https://github.com/raml2html/raml2html/issues/280 in the process?

**Comment by nickwb** [comment]
I would find it difficult to recommend that course of action. It will cause breakages for anyone using optional properties or union types. To upgrade, we probably need to write our own mechanism to go from expanded form to not-quite-canonical form.

**Comment by kevinrenskers** [comment]
If we do the `expandedForm` step but then skip the `canonicalForm` one, how would that impact raml2obj (and raml2html)?

**Comment by trevorr** [comment]
Also note that 0.2.x is much faster than earlier versions (due to a rewrite from ClojureScript to JavaScript) and fixes a number of bugs where expansion or canonicalization completed failed. raml2obj currently ignores expansion and canonicalization errors, so bugs in that may have been going unnoticed (particularly since the RAML parser started returning all types wrapped in an array, which earlier versions of datatype-expansion don't support well).

Moving to 0.2.2 causes 5 test failures (but greatly improves the results of raml2html for my API). I can look into addressing those if you're open to upgrading.

**Comment by kevinrenskers** [comment]
That would be great!

**Comment by sichvoge** [comment]
Go for it @trevorr and let us know if you need anything.

**Comment by trevorr** [comment]
With some recent fixes, the `develop` branch of datatype-expansion now passes all the raml2obj tests. Once they provide a release with those fixes, I'll submit a PR that updates the version.

I also plan to include a minor change to how the library is called. Currently, the async/callback forms of `expandedForm` and `canonicalForm` are used without any error checking. Since those callbacks are always invoked synchronously anyway, I'm going to change them to synchronous calls wrapped in a try/catch that prints errors to `console.error` (and then continues as usual). It's not ideal for a library to write to stderr, but that seems preferable to failing silently. That will make it very obvious if additional datatype-expansion fixes are needed.

**Comment by kevinrenskers** [comment]
Sounds very good.

**Comment by jstoiko** [comment]
datatype-expansion@0.2.4 [released](https://github.com/raml-org/datatype-expansion/releases/tag/v0.2.4)

**Comment by trevorr** [comment]
Hmmm, a new test failure has appeared:

```
  35 passing (689ms)
  1 failing

  1) raml2obj worldmusic.raml should test the /api methods:

      AssertionError [ERR_ASSERTION]: 'union' === 'object'
      + expected - actual

      -union
      +object

      at Context.it (test/worldmusic.spec.js:114:14)
```

**Comment by jstoiko** [comment]
weird. let me know if that’s anything on our side.

**Comment by trevorr** [comment]
It looks like the test is in error. The type in question has a union property (`CatOrDog: Cat | Dog`), and canonicalization is correctly changing the top level type to `union`. Does anyone know if the canonicalization algorithm intentionally changed in that regard since 0.0.15?

**Comment by kevinrenskers** [comment]
It's merged to develop! raml2obj 5.7.0 is ready to be merged to master and published to npm. Can someone double check that everything works with raml2html, that nothing breaks?

**Comment by kevinrenskers** [comment]
Also, @trevorr if you'd like an invite to become part of the raml2html org, let me know. Happy to add you as a contributor.

**Comment by trevorr** [comment]
raml2html works better for me, although I still get 3 canonicalization errors in `minType` (now shown on stderr, and _way_ fewer than before) from a large-ish API I'm working on:

```
Error: incompatible types: [[object Object], string]
    at minType (/Users/trevor/dev/raml2obj/node_modules/datatype-expansion/src/minType.js:302:9)
    at superPropKeys.filter.forEach (/Users/trevor/dev/raml2obj/node_modules/datatype-expansion/src/minType.js:217:24)
...
Error: incompatible types: [[object Object], string]
...
Error: incompatible types: [object, array]
    at minType (/Users/trevor/dev/raml2obj/node_modules/datatype-expansion/src/minType.js:302:9)
    at computed.anyOf.sup.anyOf.map.elem (/Users/trevor/dev/raml2obj/node_modules/datatype-expansion/src/minType.js:286:44)
...
```

This results in some properties showing up with type `[object Object]`. I'll look into fixing those.

Also, based on the `union` test I had to change above, I'm thinking about proposing that "union-hoisting" be made optional in datatype-expansion canonicalization and disabled in raml2obj. For instance, if I have an object with 15 nullable properties (with `type` of form `T?`, which gets expanded to `T | nil`), I don't want my documentation to show a union of 2<sup>15</sup> permutations. Thoughts on that?

@kevinrenskers: Sure, thanks, invite me. I've apparently got more work to do. 😄

**Comment by kevinrenskers** [comment]
By the way, we really need to remove this logging because the standard way to use raml2html is something like `raml2html example.raml > example.html`, so now that would include all this output from raml2obj. We really can't release it like that. Sorry I didn't realize that before.

**Comment by trevorr** [comment]
The logging goes to stderr, not stdout, so normal redirection is unaffected.

**Comment by kevinrenskers** [comment]
Ah that sounds good. I don't really know enough about that haha.

I'll send the invite your way, but please keep working in feature branches, don't commit directly to develop or master :)
