### ISSUE TITLE
add support for RAML 1.0

### ISSUE THREAD

**Issue by alainlecluse** [raml2html/raml2obj#3]
The RAML specifications for 1.0 are in RC now (http://docs.raml.org/specs/1.0/).

Are there any plans to support 1.0?

**Comment by sichvoge** [comment]
Yes, @alainlecluse I currently try to migrate using the beta version of the new JS parser. Don't have any timeline for this though.

**Comment by sichvoge** [comment]
How are you using that project?

**Comment by alainlecluse** [comment]
Good to hear that. 1.0 is still in RC but it has a lot of great features. 
Where using raml2html.

**Comment by jarl-dk** [comment]
:+1:

**Comment by jarl-dk** [comment]
Seems like there is a working fork at https://github.com/RemRyahirev/raml2obj/tree/master . Could you consider merge that into the official raml2obj and make a npm release

**Comment by jarl-dk** [comment]
@mikestowe: I think this issue and the fork I've mentioned above is relevant to resolve https://github.com/raml2html/raml2html/issues/156

**Comment by sichvoge** [comment]
@jarl-dk do you know if that project is tested with the existing tools that rely on it?

**Comment by kevinrenskers** [comment]
@RemRyahirev if you successfully added RAML 1 support to raml2obj, could you consider creating a pull request to share your changes?

**Comment by sichvoge** [comment]
just to remind here that i would merge it into a branch instead of master. RAML 1.0 is still in release candidate stage and there are some changes coming for RC2.

**Comment by DataGreed** [comment]
Any update on this?

**Comment by mikestowe** [comment]
RAML 1.0 support has been added to the RAML1.0 branch. You should be able to try it out using that branch, but please note that it is still under development as we wait for the RAML 1 specification to be finalized.

**Comment by DataGreed** [comment]
Oh, i thought it was finalized :) Is there any deadline on finalization,
yet?

sent from a mobile device with autocorrection
2 мая 2016 г. 6:24 PM пользователь "Michael Stowe" <notifications@github.com>
написал:

**Comment by allanhortle** [comment]
The 1.0 release was given GA status on may 16: https://github.com/raml-org/raml-spec/releases/tag/1.0

**Comment by thejmazz** [comment]
I've made [my own fork](https://github.com/thejmazz/raml2obj) which uses the AST methods rather than `toJSON` to make the object.  It's quite a divergence, but I think using the AST methods has its own advantages at the expense of being more verbose. I'm aiming to have it produce an object that js-yaml would except with types/schemas resolved. It's how I first approached it after reading the getting started guide on the parser. Even though it is quite early stage, it already supports parsing JSON Schemas (#1).

**Comment by sichvoge** [comment]
@thejmazz I think using the AST methods is a necessary step to be honest. The problem here is the expansion of types and libraries; especially libraries that the current JSON object does not cover. What would be your solution?

**Comment by thejmazz** [comment]
The way I expanded types was along the lines of was if `body.type()[0]` was not a regular type (number, string, etc) it would try to pull that definition from `api.types()`.

Not sure what libraries are..just starting to use RAML

Can you post an example of this problem?

**Comment by sichvoge** [comment]
Posted in [here](https://github.com/raml2html/raml2obj/issues/1#issuecomment-229935208)

**Comment by kevinrenskers** [comment]
Closing this ticket. Initial support for RAML 1.0 has been added in the develop branch and released as 4.0.0-beta1, and I have been hard at work to make the raml object easier to work with for clients like raml2html and raml2md. This will soon be released as 4.0.0-beta2.

It doesn't seem necessary to use the AST methods, as the raml-parser seems to handle the expansion of types and libraries just fine.

**Comment by sichvoge** [comment]
@kevinrenskers is the output of the raml2obj project significant different? would it be good to have a schema that describes what raml2obj produces. I think that could immensely improve the experience using that module

**Comment by kevinrenskers** [comment]
Mostly we just add extra stuff to the raml object, but one big difference with the raw output from the raml parser is that I made the output consistent wrt arrays, objects, objects with wrapper objects, etc etc. 

The unit tests should serve as a good source of documentation of the output format, but we can always document it more, sure.

**Comment by sichvoge** [comment]
It would be really cool to have some kind of schema. :)
