### ISSUE TITLE
Raml 1.0 Extension doesn't work

### ISSUE THREAD

**Issue by timeros07** [raml2html/raml2obj#31]
When i write
```
#%RAML 1.0  Extension
extends: ../modules/common.raml
```
paths from common.raml file is not included in results.

**Comment by nickburns2006** [comment]
I dove into this today, the problem is in the raml-1-parser dependency. The issue is referenced:  raml-org/raml-js-parser-2#658. They've released a new version 1.1.15 that fixes it.

So updating the dependency solves it. I'll submit a PR.

**Comment by nickburns2006** [comment]
PR #35
