### ISSUE TITLE
Inheritance from type "any" does not work correctly

### ISSUE THREAD

**Issue by ashlanderr** [raml2html/raml2obj#34]
If I do something like this:
```raml
types:
  BaseResponse:
    type: object
    properties:
      code: integer
      data: any
  SampleResponseData:
    type: object
    properties:
      a: string
      b: string
/example:
  get:
    responses:
      200:
        body:
          application/json:
            type: BaseResponse
            properties:
              data: SampleResponseData
```
Then field `data` does not contains properties from type `SampleResponseData` and has type `any`

**Comment by ashlanderr** [comment]
I think the problem is in types merging at https://github.com/raml2html/raml2obj/blob/master/consistency-helpers.js#L17:
```javascript
const mergedObj = Object.assign({}, obj, types[obj.type]);
```
Base type needs to be assigned before derived type. And properties (of object type) need to be recursively merged too.

**Comment by kevinrenskers** [comment]
I am going to close old issues, and will ask that new bug reports instead be created as a pull request with a failing unit test. Sorry, but I just don't have the time and energy to do it all alone :/

See also https://github.com/raml2html/raml2obj/blob/develop/CONTRIBUTING.md. Thanks!
