### ISSUE TITLE
test the new "load" function of the js parser

### ISSUE THREAD

**Issue by sichvoge** [raml2html/raml2obj#38]
Hi, the JS parser version 1.1.15 introduces a new `load` function that gives you the JSON output immediately without you having to call "parse", "expand(true)", and "toJSON". 

The JSON that is coming back is an improved version of the previous with feedback from @kevinrenskers on what he had to do in this project. It should be more consistent now.

Please test and give us feedback! :)

Schema: https://github.com/raml-org/raml-js-parser-2/blob/master/tckJSONSchema-newFormat/tckJsonSchema.json

API: https://github.com/raml-org/raml-js-parser-2/blob/master/documentation/ApiOverview.md

**Comment by kevinrenskers** [comment]
Sounds awesome!

**Comment by MichaelIT** [comment]
I am woking on it.

**Comment by kevinrenskers** [comment]
Might actually be best to wait a little bit since the parser guys are thinking about overhauling their output to make life easier for projects like ours.

**Comment by MichaelIT** [comment]
https://github.com/raml2html/raml2obj/compare/develop...MichaelIT:develop

Hi, I have change to new "load" function of the js parser. But a lot of thing need u guys to confirm😢.
And there is still one test faild. I am new in github contribution,  please let me know if u have any suggestion! @kevinrenskers @sichvoge

**Comment by sichvoge** [comment]
@MichaelIT First and foremost, thanks! :) We are actually thinking about adding more improvements to the "load" method. We have some plan in place already and if you like we can involve you in validating the interface (JSON output). Let me know.

So, let's park this issue. I am sure @kevinrenskers has other more pressing issues for you to work on ;)

Again, we are really happy for any contribution. Thanks @MichaelIT
