### ISSUE TITLE
Support baseUriParameters [moved from raml2html/raml2html]

### ISSUE THREAD

**Issue by h0ru5** [raml2html/raml2obj#4]
This is a transfer from raml2html/raml2html#99

see RAML example there, position for fixing it would probably be here:

https://github.com/raml2html/raml2obj/blob/master/index.js#L9

**Comment by h0ru5** [comment]
ok, probably need to initialize the ``allUriParameters`` with the ``baseUriParameters`` and pass them 
here:
https://github.com/raml2html/raml2obj/blob/master/index.js#L79

**Comment by garrychnca** [comment]
@kevinrenskers Will baseUriParameters be supported by the next release for spec 1.0?

**Comment by kevinrenskers** [comment]
That's the plan, yes!

**Comment by kevinrenskers** [comment]
Actually I thought this ticket was for raml2html, and that will add support for baseUriParameters. There should not be any work needed in raml2obj, so I am closing this ticket.

**Comment by h0ru5** [comment]
actually yes, raml2html/raml2html#99
